### ISSUE TITLE
Suggestion: temporary `mut`

### ISSUE THREAD

**Issue by Rudxain** [FusionSid/Rust-Learning#1]
This can be achieved via "binding shadowing" (formally), AKA "var re-declaration" (informally). This is only useful if you only need to assign once

```rust
let x = 0;
let x = x + 1;
println!("{x}"); // prints 1
```

This can also be used to "lock" `mut` vars

```rust
let mut x = 0;
for _ in 0..69 {
    // random code that mutates `x`
}
// "locks" `x` to its latest value
let x = x;
```

Immutability is good practice. But shadowing can be confusing, that's why Clippy has a `shadow_unrelated` lint, to prevent devs from doing something silly, like this

```rust
let x = 0;
let x = "bruh";
```

**There are gotchas**, so be careful

```rust
let mut x = 0;
for _ in 0..69 {
    let mut x = foobar_rng();
    // some more code that mutates `x`
}

x += 1;

// "locks" `x` to its value outside the loop scope,
// in this case, 1
let x = x;
```

I wanted to share this info, just-in-case you may need it sometime in the future

**Comment by FusionSid** [comment]
Thank you so much for sharing :) This was really interesting to read.
Kinda stopped doing rust months ago but I think i'll get back into these holidays
